# Generated by Django 5.0.6 on 2024-05-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Branch Name")),
                (
                    "branch_adress",
                    models.CharField(
                        blank=True,
                        default="1",
                        max_length=255,
                        null=True,
                        verbose_name="Adress",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "3.Branchs",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("expiration_date", models.DateTimeField()),
                (
                    "users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Last Name "
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email "
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number ",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adress "),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=50,
                        verbose_name="Gender ",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="Profile Photo ",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "applied_coupons",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.coupon",
                        verbose_name="Applied coupons ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "1.Customers",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Room Name")),
                (
                    "room_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="Room Cost/H ",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.branch",
                        verbose_name="Branch Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "4.Rooms",
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Desk Name")),
                (
                    "desk_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="Desk Cost/H ",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.room",
                        verbose_name="Room Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desk",
                "verbose_name_plural": "6.Desks",
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Space Name")),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Slogan"
                    ),
                ),
                (
                    "space_adress",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Adress"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.customer",
                        verbose_name="Owner Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Space",
                "verbose_name_plural": "2.Spaces",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="space",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.space",
                verbose_name="Space",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="space_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.space",
                verbose_name="Space",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.space",
                verbose_name="Space",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.space",
                verbose_name="Space",
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Table Name")),
                (
                    "table_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="Table Cost/H ",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.branch",
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.room",
                        verbose_name="Room Name",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.space",
                        verbose_name="Space",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "5.Tables",
            },
        ),
    ]
