# Generated by Django 5.0.6 on 2024-05-26 21:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("booking_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Customer Phone ",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Customer E-mail ",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(
                        blank=True, default="00:00", null=True, verbose_name="Check in "
                    ),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True,
                        default="00:00",
                        null=True,
                        verbose_name="Check out ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Shared", "Shared"), ("Private", "Private")],
                        default="Shared",
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Cost ")),
                ("discount", models.IntegerField(default=0)),
                (
                    "want_reminder",
                    models.BooleanField(default=False, verbose_name="Want Reminder"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                limit_value=500, message="Message is too long"
                            )
                        ],
                        verbose_name="additional info  ",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.branch",
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.coupon",
                        verbose_name="Coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.customer",
                        verbose_name="Customer Name ",
                    ),
                ),
                (
                    "desk_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.desk",
                        verbose_name="Desk Number ",
                    ),
                ),
                (
                    "room_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.room",
                        verbose_name="Room Number ",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.space",
                        verbose_name="Space",
                    ),
                ),
                (
                    "table_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="space.table",
                        verbose_name="Table Number ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservation",
            },
        ),
    ]
