# Generated by Django 5.0.6 on 2024-05-25 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("expiration_date", models.DateTimeField()),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="coupons", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("booking_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Customer Phone ",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Customer E-mail ",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(
                        blank=True, default="00:00", null=True, verbose_name="Check in "
                    ),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True,
                        default="00:00",
                        null=True,
                        verbose_name="Check out ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Shared", "Shared"), ("Private", "Private")],
                        default="Shared",
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Cost ")),
                ("discount", models.IntegerField(default=0)),
                (
                    "want_reminder",
                    models.BooleanField(default=False, verbose_name="Want Reminder"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                limit_value=500, message="Message is too long"
                            )
                        ],
                        verbose_name="additional info  ",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.coupon",
                        verbose_name="Coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservation",
            },
        ),
    ]
