# Generated by Django 5.0.6 on 2024-05-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservation", "0001_initial"),
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="space.customer",
                verbose_name="Customer Name ",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="desk_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.desk",
                verbose_name="Desk Number ",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="room_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.room",
                verbose_name="Room Number ",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.table",
                verbose_name="Table Number ",
            ),
        ),
    ]
