# Generated by Django 5.0.6 on 2024-05-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.coupon",
                verbose_name="Coupon",
            ),
        ),
    ]
