# Generated by Django 5.0.6 on 2024-05-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_initial"),
        ("space", "0003_room_space"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="space",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.space",
                verbose_name="Space",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
